#!/usr/bin/env python3
"""
Generate Obsidian vault from FORGE documents.

This script transforms FORGE's agent-optimized markdown files into an Obsidian vault
with wiki-links, YAML frontmatter, MOCs, graph styling, and dataview queries - without
modifying any source FORGE documents.

Usage:
    python forge/scripts/generate_vault.py --output .forge-vault
    python forge/scripts/generate_vault.py --output ~/Documents/ObsidianVaults/forge
    python forge/scripts/generate_vault.py --output .forge-vault --force
    python forge/scripts/generate_vault.py --output .forge-vault --dry-run
"""

import argparse
import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


class VaultGenerator:
    """Generate Obsidian vault from FORGE documents."""

    GENERATED_MARKER = "<!-- GENERATED by forge/scripts/generate_vault.py - DO NOT EDIT -->"

    # Wiki-link mappings for file path conversions
    WIKILINK_MAPPINGS = {
        "forge/FORGE.md": "FORGE-Protocol",
        "forge/CLAUDE.md": "CLAUDE-Manual",
        "forge/global/architecture.md": "Architecture",
        "forge/global/constraints.md": "Constraints",
        "forge/global/verification.md": "Verification",
        "AGENTS.md": "AGENTS",
        "ARCHITECTURE.md": "ARCHITECTURE",
    }

    def __init__(self, forge_root: Path, output_path: Path, force: bool = False, dry_run: bool = False):
        self.forge_root = forge_root
        self.output_path = output_path
        self.force = force
        self.dry_run = dry_run
        self.changes_dir = forge_root / "forge" / "changes"
        self.global_dir = forge_root / "forge" / "global"
        self.forge_dir = forge_root / "forge"

    def generate(self):
        """Main generation orchestrator."""
        print(f"\n🔨 FORGE Obsidian Vault Generator")
        print(f"   Source: {self.forge_root}")
        print(f"   Output: {self.output_path}")
        print(f"   Mode: {'DRY RUN' if self.dry_run else 'FORCE' if self.force else 'SMART MERGE'}\n")

        # Validate FORGE structure
        if not self._validate_forge_structure():
            print("✗ Invalid FORGE structure. Aborting.")
            sys.exit(1)

        # Handle force mode
        if self.force and self.output_path.exists() and not self.dry_run:
            print(f"🗑  Force mode: removing existing vault at {self.output_path}")
            shutil.rmtree(self.output_path)

        # Create vault directories
        self._create_vault_structure()

        # Generate .obsidian config
        self._generate_obsidian_config()

        # Transform core docs
        self._transform_core_docs()

        # Transform changes
        self._transform_changes()

        # Generate MOCs
        self._generate_mocs()

        # Generate canvas
        self._generate_canvas()

        # Create templates (if missing)
        self._create_templates()

        print(f"\n✓ Vault generation complete!")
        if not self.dry_run:
            print(f"  Open {self.output_path} in Obsidian to explore.")

    def _validate_forge_structure(self) -> bool:
        """Validate that FORGE structure exists."""
        required = [
            self.forge_dir / "FORGE.md",
            self.forge_dir / "CLAUDE.md",
            self.global_dir / "architecture.md",
            self.global_dir / "constraints.md",
            self.global_dir / "verification.md",
            self.changes_dir,
        ]
        for path in required:
            if not path.exists():
                print(f"✗ Missing required file: {path}")
                return False
        return True

    def _create_vault_structure(self):
        """Create vault directory structure."""
        dirs = [
            self.output_path / ".obsidian",
            self.output_path / ".obsidian" / "plugins",
            self.output_path / ".obsidian" / "snippets",
            self.output_path / "_meta",
            self.output_path / "_templates",
            self.output_path / "_canvas",
            self.output_path / "_custom",
            self.output_path / "core",
            self.output_path / "changes",
        ]
        for d in dirs:
            if self.dry_run:
                print(f"  [dry-run] Would create: {d}")
            else:
                d.mkdir(parents=True, exist_ok=True)
                print(f"  ✓ Created: {d}")

    def _generate_obsidian_config(self):
        """Generate Obsidian configuration files."""
        # Workspace layout
        workspace = {
            "main": {
                "id": "forge-main",
                "type": "split",
                "children": [
                    {
                        "id": "file-explorer",
                        "type": "leaf",
                        "state": {"type": "file-explorer"}
                    },
                    {
                        "id": "graph-view",
                        "type": "leaf",
                        "state": {"type": "graph"}
                    }
                ]
            }
        }
        self._write_json(self.output_path / ".obsidian" / "workspace.json", workspace)

        # Graph view settings
        graph = {
            "collapse-filter": False,
            "search": "",
            "localBacklinks": True,
            "localForelinks": True,
            "localInterlinks": False,
            "showTags": True,
            "showAttachments": False,
            "hideUnresolved": False,
            "showOrphans": True,
            "collapse-color-groups": False,
            "colorGroups": [
                {"query": "tag:#forge/core", "color": {"a": 1, "rgb": 3847330}},
                {"query": "tag:#phase/execute", "color": {"a": 1, "rgb": 1097537}},
                {"query": "tag:#phase/review", "color": {"a": 1, "rgb": 16158475}},
                {"query": "tag:#phase/blocked", "color": {"a": 1, "rgb": 15680324}},
                {"query": "tag:#phase/done", "color": {"a": 1, "rgb": 7039851}}
            ],
            "collapse-display": False,
            "showArrow": True,
            "textFadeMultiplier": 0,
            "nodeSizeMultiplier": 1,
            "lineSizeMultiplier": 1,
            "collapse-forces": False,
            "centerStrength": 0.518713248970312,
            "repelStrength": 10,
            "linkStrength": 1,
            "linkDistance": 250,
            "scale": 1,
            "close": False
        }
        self._write_json(self.output_path / ".obsidian" / "graph.json", graph)

        # CSS snippets
        self._write_css_snippets()

    def _write_css_snippets(self):
        """Write CSS snippets for graph styling."""
        graph_css = """/* FORGE Graph View Styling */

/* Phase-based node colors */
.graph-view.color-fill[data-tag*="phase/plan"] { fill: #3b82f6; }
.graph-view.color-fill[data-tag*="phase/review"] { fill: #f59e0b; }
.graph-view.color-fill[data-tag*="phase/execute"] { fill: #10b981; }
.graph-view.color-fill[data-tag*="phase/blocked"] { fill: #ef4444; }
.graph-view.color-fill[data-tag*="phase/done"] { fill: #6b7280; }

/* Type-based node sizes */
.graph-view.color-fill[data-tag*="forge/core"] { r: 8; }
.graph-view.color-fill[data-tag*="forge/spec"] { r: 6; }
.graph-view.color-fill[data-tag*="forge/moc"] { r: 10; }
"""
        self._write_file(self.output_path / ".obsidian" / "snippets" / "forge-graph.css", graph_css)

    def _transform_core_docs(self):
        """Transform core FORGE docs to vault."""
        print("\n📄 Transforming core documents...")

        docs = [
            (self.forge_dir / "FORGE.md", "FORGE-Protocol.md", "protocol-doc", ["forge/core", "protocol"]),
            (self.forge_dir / "CLAUDE.md", "CLAUDE-Manual.md", "agent-manual", ["forge/core", "agent"]),
            (self.global_dir / "architecture.md", "Architecture.md", "architecture", ["forge/core", "architecture"]),
            (self.global_dir / "constraints.md", "Constraints.md", "constraints", ["forge/core", "constraints"]),
            (self.global_dir / "verification.md", "Verification.md", "verification", ["forge/core", "verification"]),
        ]

        for source, dest_name, doc_type, tags in docs:
            if not source.exists():
                print(f"  ⚠ Skipping missing: {source}")
                continue

            content = source.read_text()
            metadata = {
                "type": doc_type,
                "category": "core",
                "tags": tags,
                "source": str(source.relative_to(self.forge_root)),
                "generated": datetime.now(timezone.utc).isoformat(),
            }

            # Add aliases
            if dest_name == "FORGE-Protocol.md":
                metadata["aliases"] = ["FORGE", "Protocol"]
            elif dest_name == "CLAUDE-Manual.md":
                metadata["aliases"] = ["CLAUDE", "Agent Manual"]

            transformed = self._add_frontmatter(content, metadata)
            transformed = self._convert_file_refs_to_wikilinks(transformed)
            transformed = self._add_generated_marker(transformed, source)

            dest = self.output_path / "core" / dest_name
            self._write_file(dest, transformed)
            print(f"  ✓ {source.name} → core/{dest_name}")

    def _transform_changes(self):
        """Transform all changes to vault."""
        print("\n📦 Transforming changes...")

        if not self.changes_dir.exists():
            print("  No changes directory found")
            return

        change_count = 0
        for change_dir in sorted(self.changes_dir.iterdir()):
            if not change_dir.is_dir() or change_dir.name.startswith("."):
                continue

            state_file = change_dir / "state.json"
            if not state_file.exists():
                continue

            self._transform_change(change_dir)
            change_count += 1

        print(f"  ✓ Transformed {change_count} changes")

    def _transform_change(self, change_dir: Path):
        """Transform a single change directory."""
        change_id = change_dir.name
        state = self._load_state(change_dir)
        phase = state.get("phase", "unknown") if state else "unknown"

        vault_change_dir = self.output_path / "changes" / change_id
        if not self.dry_run:
            vault_change_dir.mkdir(parents=True, exist_ok=True)

        # Transform spec.md
        spec_file = change_dir / "spec.md"
        if spec_file.exists():
            content = spec_file.read_text()
            requirements_count = len(re.findall(r"^\d+\.", content, re.MULTILINE))

            metadata = {
                "type": "specification",
                "change_id": change_id,
                "phase": phase,
                "tags": ["forge/spec", f"phase/{phase}", f"change/{change_id}"],
                "aliases": [f"{change_id} spec"],
                "source": str(spec_file.relative_to(self.forge_root)),
                "generated": datetime.now(timezone.utc).isoformat(),
                "total_requirements": requirements_count,
            }

            transformed = self._add_frontmatter(content, metadata)
            transformed = self._convert_file_refs_to_wikilinks(transformed)
            transformed = self._add_generated_marker(transformed, spec_file)

            self._write_file(vault_change_dir / "spec.md", transformed)

        # Transform tasks.md
        tasks_file = change_dir / "tasks.md"
        if tasks_file.exists():
            content = tasks_file.read_text()
            task_counts = self._count_tasks(content)

            metadata = {
                "type": "task-list",
                "change_id": change_id,
                "phase": phase,
                "tags": ["forge/tasks", f"phase/{phase}", f"change/{change_id}"],
                "source": str(tasks_file.relative_to(self.forge_root)),
                "generated": datetime.now(timezone.utc).isoformat(),
                **task_counts,
            }

            transformed = self._add_frontmatter(content, metadata)
            transformed = self._convert_file_refs_to_wikilinks(transformed)
            transformed = self._add_generated_marker(transformed, tasks_file)

            self._write_file(vault_change_dir / "tasks.md", transformed)

        # Transform decisions.md
        decisions_file = change_dir / "decisions.md"
        if decisions_file.exists():
            content = decisions_file.read_text()

            metadata = {
                "type": "decision-log",
                "change_id": change_id,
                "phase": phase,
                "tags": ["forge/decisions", f"change/{change_id}"],
                "source": str(decisions_file.relative_to(self.forge_root)),
                "generated": datetime.now(timezone.utc).isoformat(),
            }

            transformed = self._add_frontmatter(content, metadata)
            transformed = self._convert_file_refs_to_wikilinks(transformed)
            transformed = self._add_generated_marker(transformed, decisions_file)

            self._write_file(vault_change_dir / "decisions.md", transformed)

        # Generate _index.md
        self._generate_change_index(change_dir, vault_change_dir, state)

    def _generate_change_index(self, source_dir: Path, dest_dir: Path, state: dict | None):
        """Generate index file for a change."""
        change_id = source_dir.name
        phase = state.get("phase", "unknown") if state else "unknown"
        current_task = state.get("current_task", "none") if state else "none"
        last_updated = state.get("last_updated", "unknown") if state else "unknown"

        tasks_file = source_dir / "tasks.md"
        task_counts = self._count_tasks(tasks_file.read_text()) if tasks_file.exists() else {}

        total = task_counts.get("total_tasks", 0)
        completed = task_counts.get("completed", 0)

        content = f"""---
type: change-index
change_id: "{change_id}"
phase: "{phase}"
tags: [forge/change, phase/{phase}]
generated: {datetime.now(timezone.utc).isoformat()}
---

# Change: {change_id}

**Phase**: `{phase.upper()}` | **Current Task**: {current_task} | **Updated**: {last_updated}

## Quick Links

- [[spec|📋 Specification]]
- [[tasks|✅ Tasks]] ({completed}/{total} complete)
- [[decisions|💡 Decisions]]

## Status

- ✅ Completed: {task_counts.get('completed', 0)} tasks
- ⏳ Pending: {task_counts.get('pending', 0)} tasks
- 🚧 Blocked: {task_counts.get('blocked', 0)} tasks
- 🔄 In Progress: {task_counts.get('in_progress', 0)} tasks

## Related

- [[Architecture]]
- [[Constraints]]
- [[Verification]]
"""

        content = self._add_generated_marker(content, source_dir / "_index.md")
        self._write_file(dest_dir / "_index.md", content)

    def _generate_mocs(self):
        """Generate Maps of Content."""
        print("\n🗺  Generating MOCs...")

        self._generate_readme()
        self._generate_active_changes_moc()
        self._generate_architecture_index()
        self._generate_phase_dashboard()

    def _generate_readme(self):
        """Generate vault README entry point."""
        content = f"""---
type: moc
category: entry-point
tags: [forge/moc]
generated: {datetime.now(timezone.utc).isoformat()}
---

# FORGE Vault

Welcome to the FORGE protocol documentation vault.

## Quick Navigation

- [[FORGE-Protocol]] - Protocol overview
- [[01-Active-Changes]] - Current work
- [[02-Architecture-Index]] - System architecture
- [[CLAUDE-Manual]] - Agent operating manual

## By Phase

- [[03-Phase-Dashboard]] - Visual status board

## Core Documentation

- [[Architecture]] - System architecture
- [[Constraints]] - Global constraints
- [[Verification]] - Quality gates

## Custom Notes

Add your own notes in the `_custom/` folder - they will be preserved across vault updates.
"""

        content = self._add_generated_marker(content, Path("_meta/00-README.md"))
        self._write_file(self.output_path / "_meta" / "00-README.md", content)
        print("  ✓ 00-README.md")

    def _generate_active_changes_moc(self):
        """Generate active changes MOC."""
        if not self.changes_dir.exists():
            return

        changes_by_phase = {
            "execute": [],
            "review": [],
            "plan": [],
            "blocked": [],
            "done": [],
        }

        for change_dir in sorted(self.changes_dir.iterdir()):
            if not change_dir.is_dir() or change_dir.name.startswith("."):
                continue

            state = self._load_state(change_dir)
            if not state:
                continue

            phase = state.get("phase", "unknown").lower()
            change_id = change_dir.name
            current_task = state.get("current_task", "none")
            last_updated = state.get("last_updated", "unknown")

            tasks_file = change_dir / "tasks.md"
            task_counts = self._count_tasks(tasks_file.read_text()) if tasks_file.exists() else {}

            change_info = {
                "id": change_id,
                "phase": phase,
                "current_task": current_task,
                "updated": last_updated,
                "counts": task_counts,
            }

            if phase in changes_by_phase:
                changes_by_phase[phase].append(change_info)

        content = f"""---
type: moc
category: active-changes
tags: [forge/moc]
generated: {datetime.now(timezone.utc).isoformat()}
---

# Active Changes

"""

        # In Progress
        if changes_by_phase["execute"]:
            content += "## 🔄 In Progress\n\n"
            for change in changes_by_phase["execute"]:
                counts = change["counts"]
                total = counts.get("total_tasks", 0)
                completed = counts.get("completed", 0)
                pending = counts.get("pending", 0)
                blocked = counts.get("blocked", 0)

                content += f"- [[changes/{change['id']}/_index|{change['id']}]] - Phase: `EXECUTE` - Task {completed}/{total}\n"
                content += f"  - Status: ✅ {completed} done · ⏳ {pending} pending · 🚧 {blocked} blocked\n"
                content += f"  - [[changes/{change['id']}/spec|Spec]] | [[changes/{change['id']}/tasks|Tasks]] | [[changes/{change['id']}/decisions|Decisions]]\n\n"

        # In Review
        if changes_by_phase["review"]:
            content += "## 📋 In Review\n\n"
            for change in changes_by_phase["review"]:
                content += f"- [[changes/{change['id']}/_index|{change['id']}]] - Phase: `REVIEW` - Awaiting approval\n"
                content += f"  - [[changes/{change['id']}/spec|Spec]] | [[changes/{change['id']}/tasks|Tasks]]\n\n"

        # Blocked
        if changes_by_phase["blocked"]:
            content += "## 🚧 Blocked\n\n"
            for change in changes_by_phase["blocked"]:
                content += f"- [[changes/{change['id']}/_index|{change['id']}]] - Phase: `BLOCKED`\n"
                content += f"  - [[changes/{change['id']}/spec|Spec]] | [[changes/{change['id']}/tasks|Tasks]]\n\n"

        # Recently Completed
        done_changes = sorted(changes_by_phase["done"], key=lambda x: x["updated"], reverse=True)[:5]
        if done_changes:
            content += "## ✅ Recently Completed\n\n"
            for change in done_changes:
                content += f"- [[changes/{change['id']}/_index|{change['id']}]] - Completed: {change['updated']}\n"

        content = self._add_generated_marker(content, Path("_meta/01-Active-Changes.md"))
        self._write_file(self.output_path / "_meta" / "01-Active-Changes.md", content)
        print("  ✓ 01-Active-Changes.md")

    def _generate_architecture_index(self):
        """Generate architecture index MOC."""
        content = f"""---
type: moc
category: architecture
tags: [forge/moc, architecture]
generated: {datetime.now(timezone.utc).isoformat()}
---

# Architecture Index

## Core Architecture Documents

- [[Architecture]] - System architecture and module map
- [[Constraints]] - Global constraints and rules
- [[Verification]] - Quality gates and verification protocol

## Protocol Documentation

- [[FORGE-Protocol]] - Complete FORGE protocol reference
- [[CLAUDE-Manual]] - Agent operating manual

## Related

- [[00-README]] - Vault entry point
- [[01-Active-Changes]] - Current work
"""

        content = self._add_generated_marker(content, Path("_meta/02-Architecture-Index.md"))
        self._write_file(self.output_path / "_meta" / "02-Architecture-Index.md", content)
        print("  ✓ 02-Architecture-Index.md")

    def _generate_phase_dashboard(self):
        """Generate phase dashboard with dataview queries."""
        content = f"""---
type: dashboard
tags: [forge/dashboard]
generated: {datetime.now(timezone.utc).isoformat()}
---

# Phase Dashboard

## By Phase

### Execute Phase

```dataview
TABLE
  total_tasks as "Tasks",
  completed as "Done",
  pending as "Pending",
  blocked as "Blocked"
FROM "changes"
WHERE type = "task-list" AND phase = "execute"
SORT file.name ASC
```

### Review Phase

```dataview
LIST
FROM "changes"
WHERE type = "specification" AND phase = "review"
```

### Blocked

```dataview
LIST
FROM "changes"
WHERE type = "specification" AND phase = "blocked"
```

### Recently Completed

```dataview
TABLE generated as "Completed"
FROM "changes"
WHERE type = "specification" AND phase = "done"
SORT generated DESC
LIMIT 10
```

## Task Status Overview

```dataview
TABLE
  change_id as "Change",
  phase as "Phase",
  completed as "✅",
  pending as "⏳",
  blocked as "🚧"
FROM "changes"
WHERE type = "task-list"
SORT phase ASC, change_id ASC
```
"""

        content = self._add_generated_marker(content, Path("_meta/03-Phase-Dashboard.md"))
        self._write_file(self.output_path / "_meta" / "03-Phase-Dashboard.md", content)
        print("  ✓ 03-Phase-Dashboard.md")

    def _generate_canvas(self):
        """Generate canvas files."""
        print("\n🎨 Generating canvas...")

        # System overview canvas
        canvas = {
            "nodes": [
                {
                    "id": "forge-protocol",
                    "type": "file",
                    "file": "core/FORGE-Protocol.md",
                    "x": 0,
                    "y": 0,
                    "width": 400,
                    "height": 300,
                    "color": "1"
                },
                {
                    "id": "architecture",
                    "type": "file",
                    "file": "core/Architecture.md",
                    "x": 500,
                    "y": 0,
                    "width": 400,
                    "height": 300,
                    "color": "2"
                },
                {
                    "id": "constraints",
                    "type": "file",
                    "file": "core/Constraints.md",
                    "x": 0,
                    "y": 400,
                    "width": 400,
                    "height": 300,
                    "color": "3"
                },
                {
                    "id": "verification",
                    "type": "file",
                    "file": "core/Verification.md",
                    "x": 500,
                    "y": 400,
                    "width": 400,
                    "height": 300,
                    "color": "4"
                }
            ],
            "edges": [
                {"id": "e1", "fromNode": "forge-protocol", "toNode": "architecture"},
                {"id": "e2", "fromNode": "forge-protocol", "toNode": "constraints"},
                {"id": "e3", "fromNode": "forge-protocol", "toNode": "verification"}
            ]
        }

        self._write_json(self.output_path / "_canvas" / "system-overview.canvas", canvas)
        print("  ✓ system-overview.canvas")

    def _create_templates(self):
        """Create Obsidian templates if missing."""
        print("\n📝 Creating templates...")

        {% raw -%}
        templates = {
            "manual-note.md": """---
type: manual-note
tags: [custom]
created: {{date}}
---

# {{title}}

## Notes

""",
            "meeting-note.md": """---
type: meeting-note
tags: [custom, meeting]
created: {{date}}
related_change:
---

# Meeting: {{title}}

## Attendees

## Discussion

## Action Items

- [ ]

## Related

"""
        }
        {% endraw %}

        for name, content in templates.items():
            path = self.output_path / "_templates" / name
            if not path.exists() or self.force:
                self._write_file(path, content)
                print(f"  ✓ {name}")
            else:
                print(f"  ⊘ Skipped (exists): {name}")

    # Helper methods

    def _add_frontmatter(self, content: str, metadata: dict) -> str:
        """Add YAML frontmatter to content."""
        yaml_lines = ["---"]
        for key, value in metadata.items():
            if isinstance(value, list):
                yaml_lines.append(f"{key}: [{', '.join(str(v) for v in value)}]")
            elif isinstance(value, str):
                yaml_lines.append(f'{key}: "{value}"')
            else:
                yaml_lines.append(f"{key}: {value}")
        yaml_lines.append("---")
        yaml_lines.append("")

        return "\n".join(yaml_lines) + content

    def _add_generated_marker(self, content: str, source: Path) -> str:
        """Add generated marker to content."""
        marker = f"{self.GENERATED_MARKER}\n"
        marker += f"<!-- Source: {source} | Last generated: {datetime.now(timezone.utc).isoformat()} -->\n\n"
        return marker + content

    def _convert_file_refs_to_wikilinks(self, content: str) -> str:
        """Convert file path references to wiki-links."""
        # Convert explicit mappings
        for path, wikilink in self.WIKILINK_MAPPINGS.items():
            content = content.replace(f"`{path}`", f"[[{wikilink}]]")

        # Convert common patterns
        content = re.sub(r"`spec\.md`", "[[spec]]", content)
        content = re.sub(r"`tasks\.md`", "[[tasks]]", content)
        content = re.sub(r"`decisions\.md`", "[[decisions]]", content)
        content = re.sub(r"`state\.json`", "`state.json`", content)  # Keep state.json as-is

        return content

    def _count_tasks(self, content: str) -> dict:
        """Count task statuses from tasks.md content."""
        return {
            "total_tasks": len(re.findall(r"- status:", content)),
            "pending": len(re.findall(r"- status: \[ \]", content)),
            "completed": len(re.findall(r"- status: \[x\]", content)),
            "blocked": len(re.findall(r"- status: \[!\]", content)),
            "in_progress": len(re.findall(r"- status: \[~\]", content)),
        }

    def _load_state(self, change_dir: Path) -> dict | None:
        """Load state.json from change directory."""
        state_file = change_dir / "state.json"
        if not state_file.exists():
            return None
        try:
            return json.loads(state_file.read_text())
        except json.JSONDecodeError:
            return None

    def _write_file(self, path: Path, content: str):
        """Write file with dry-run support."""
        if self.dry_run:
            print(f"  [dry-run] Would write: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    def _write_json(self, path: Path, data: dict):
        """Write JSON file with dry-run support."""
        if self.dry_run:
            print(f"  [dry-run] Would write JSON: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(data, indent=2))


def main():
    parser = argparse.ArgumentParser(
        description="Generate Obsidian vault from FORGE documents",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python forge/scripts/generate_vault.py --output .forge-vault
  python forge/scripts/generate_vault.py --output ~/Documents/ObsidianVaults/forge
  python forge/scripts/generate_vault.py --output .forge-vault --force
  python forge/scripts/generate_vault.py --output .forge-vault --dry-run
        """
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output path for the generated vault"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force full regeneration (delete and recreate vault)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes without writing files"
    )

    args = parser.parse_args()

    # Determine forge root (assume script is in forge/scripts/)
    script_dir = Path(__file__).parent
    forge_root = script_dir.parent.parent

    generator = VaultGenerator(
        forge_root=forge_root,
        output_path=args.output,
        force=args.force,
        dry_run=args.dry_run
    )

    try:
        generator.generate()
    except KeyboardInterrupt:
        print("\n\n⚠ Interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
